import React from 'react';
import Navbar from '../../components/common/Navbar.jsx';
import { useTheme } from '../../context/ThemeContext.jsx';
import { motion } from 'framer-motion';

const FeaturesPage = () => {
  const { theme } = useTheme();

  const features = [
    {
      icon: '🤖',
      title: 'AI-Powered Learning',
      description: 'Personalized learning paths generated by advanced AI based on your resume, skills, and career goals',
      color: 'from-blue-500 to-cyan-500'
    },
    {
      icon: '📊',
      title: 'Smart Resume Analysis',
      description: 'ATS-optimized resume scanning with detailed feedback on strengths, weaknesses, and improvement areas',
      color: 'from-purple-500 to-pink-500'
    },
    {
      icon: '🎯',
      title: 'Skill Gap Identification',
      description: 'Identify missing skills for your target role with curated resources and estimated learning times',
      color: 'from-green-500 to-emerald-500'
    },
    {
      icon: '🗺️',
      title: '12-Month Career Roadmap',
      description: 'Comprehensive roadmap from beginner to placement-ready with phase-wise goals and milestones',
      color: 'from-orange-500 to-red-500'
    },
    {
      icon: '📚',
      title: 'Free Course Recommendations',
      description: 'Curated courses from Harvard, MIT, Stanford, and top platforms - all completely free',
      color: 'from-indigo-500 to-purple-500'
    },
    {
      icon: '🏆',
      title: 'Industry Certifications',
      description: 'Guidance on AWS, Google Cloud, Azure, and other high-value certifications with prep resources',
      color: 'from-yellow-500 to-orange-500'
    },
    {
      icon: '💻',
      title: 'Coding Practice Resources',
      description: 'Access to LeetCode, NeetCode, Striver DSA Sheet, and other essential interview prep platforms',
      color: 'from-teal-500 to-green-500'
    },
    {
      icon: '🚀',
      title: 'Real Project Ideas',
      description: 'Portfolio-ready projects with GitHub source code, tech stacks, and learning outcomes',
      color: 'from-pink-500 to-rose-500'
    },
    {
      icon: '💼',
      title: 'Placement Preparation',
      description: 'Mock interviews, DSA progress tracking, and direct links to top company job postings',
      color: 'from-blue-500 to-indigo-500'
    },
    {
      icon: '💡',
      title: 'Top Internship Opportunities',
      description: 'Curated internships from Google, Microsoft, Amazon, and leading startups with direct apply links',
      color: 'from-cyan-500 to-blue-500'
    },
    {
      icon: '🎨',
      title: 'Beautiful UI/UX',
      description: '5 premium themes with smooth animations and responsive design for the best learning experience',
      color: 'from-violet-500 to-purple-500'
    },
    {
      icon: '📈',
      title: 'Progress Tracking',
      description: 'Visual dashboards to track your learning progress, goals, and achievements over time',
      color: 'from-emerald-500 to-teal-500'
    }
  ];

  return (
    <div className="min-h-screen theme-bg" data-theme={theme}>
      <Navbar />
      <div className="mx-auto max-w-7xl px-4 pt-24 pb-16">
        {/* Header */}
        <motion.div 
          className="text-center mb-16"
          initial={{ opacity: 0, y: -20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6 }}
        >
          <h1 className="text-5xl font-bold mb-4 bg-gradient-to-r from-indigo-400 to-purple-400 bg-clip-text text-transparent">
            Powerful Features
          </h1>
          <p className="text-lg theme-text-muted max-w-3xl mx-auto">
            Everything you need to accelerate your learning journey and land your dream tech job
          </p>
        </motion.div>

        {/* Features Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {features.map((feature, idx) => (
            <motion.div
              key={idx}
              className="theme-card p-6 border border-slate-700 hover:border-indigo-500 transition-all"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: idx * 0.1, duration: 0.5 }}
              whileHover={{ scale: 1.05, boxShadow: '0 0 30px rgba(99, 102, 241, 0.3)' }}
            >
              <div className={`w-16 h-16 rounded-2xl bg-gradient-to-br ${feature.color} flex items-center justify-center text-3xl mb-4`}>
                {feature.icon}
              </div>
              <h3 className="text-xl font-bold mb-3">{feature.title}</h3>
              <p className="text-sm theme-text-muted leading-relaxed">
                {feature.description}
              </p>
            </motion.div>
          ))}
        </div>

        {/* CTA Section */}
        <motion.div 
          className="mt-16 text-center theme-card p-12 border border-indigo-500/30"
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 1.2 }}
        >
          <h2 className="text-3xl font-bold mb-4">Ready to Start Your Journey?</h2>
          <p className="text-lg theme-text-muted mb-8 max-w-2xl mx-auto">
            Join thousands of students already transforming their careers with LearnBridge+
          </p>
          <motion.a
            href="/auth/student"
            className="inline-block px-8 py-4 bg-gradient-to-r from-indigo-500 to-purple-500 text-white font-bold rounded-lg text-lg"
            whileHover={{ scale: 1.1, boxShadow: '0 0 30px rgba(99, 102, 241, 0.6)' }}
            whileTap={{ scale: 0.95 }}
          >
            Get Started Free →
          </motion.a>
        </motion.div>
      </div>
    </div>
  );
};

export default FeaturesPage;
